version: '3.7'

services:  
  devenv:
    build:
      context: .
      dockerfile: Dockerfile.Dev
    ports:
      - "9229:9229" #debug port
      - "4200:4200" #ng port
    environment:
      NODE_ENV: development
    volumes:
      - .:/usr/src/app
      - app_node_modules:/usr/src/app/node_modules
    command: /bin/sh -c "ng serve --host=0.0.0.0" #command for developent environment
    #command: /bin/sh -c "tail -f /dev/null" #command for developent environment
    
volumes:
  app_node_modules: