#TODO: should be node:10.16.0
FROM node:10
EXPOSE 4200

WORKDIR /usr/src/app

COPY ["package.json", "yarn.lock*","./"]

# install app dependencies...
RUN yarn install
RUN yarn global add @angular/cli@9
